---
 - hosts: all
   gather_facts: yes
   become: yes
   tasks:
     - name: Patch host
       apt: 
         update_cache: yes
         upgrade: dist
         
     
     
     - name: Install apache
       apt: 
         name: vsftpd
         state: present
