---
 - hosts: all
   gather_facts: yes
   become: yes
   tasks:
     - name: Update Cache
       apt:
         update_cache: yes
         
     - name: Patch host
       apt: 
         update_cache: yes
         upgrade: yes
         dist_upgrade: yes
     
     
     - name: Install apache
       apt: 
         name: vsftpd
         state: present
